import Link from 'next/link';
import { Swords, TrendingUp, Brain } from 'lucide-react';

export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 to-gray-800 text-white">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <div className="text-center">
          <h1 className="text-6xl font-bold mb-4">FightIQ</h1>
          <p className="text-xl text-gray-300 mb-8">
            Data-driven UFC predictions powered by AI
          </p>
          
          <Link
            href="/matchup"
            className="inline-block px-8 py-4 bg-blue-600 hover:bg-blue-700 rounded-lg font-semibold text-lg transition"
          >
            Build a Matchup
          </Link>
        </div>

        <div className="mt-20 grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="bg-gray-800 p-6 rounded-lg">
            <Swords className="w-12 h-12 text-blue-500 mb-4" />
            <h3 className="text-xl font-bold mb-2">Compare Fighters</h3>
            <p className="text-gray-400">
              Select any two fighters and see detailed statistical comparisons
            </p>
          </div>

          <div className="bg-gray-800 p-6 rounded-lg">
            <TrendingUp className="w-12 h-12 text-green-500 mb-4" />
            <h3 className="text-xl font-bold mb-2">Win Probabilities</h3>
            <p className="text-gray-400">
              Get data-driven predictions based on historical performance
            </p>
          </div>

          <div className="bg-gray-800 p-6 rounded-lg">
            <Brain className="w-12 h-12 text-purple-500 mb-4" />
            <h3 className="text-xl font-bold mb-2">AI Breakdowns</h3>
            <p className="text-gray-400">
              Read analyst-style previews generated by Claude AI
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}